name: Build, Test and Publish

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up GitHub User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Configure .npmrc
        run: |
          echo "@grupoboticario:registry=https://npm.pkg.github.com/" >  ~/.npmrc
          echo "@oeduardoal:registry=https://npm.pkg.github.com/"     >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN"    >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: yarn install --frozen-lockfile --check-files

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Release
        if: github.ref == 'refs/heads/main'
        run: |
          HUSKY=0 yarn run standard-version
          HUSKY=0 git push --follow-tags origin main
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for github-release
